"""Tests for the full run_cmd flow of rlsbl.commands.pre_push_check."""

import json

import pytest

from conftest import run_git as _run_git, git_head as _git_head
from rlsbl.commands.pre_push_check import (
    _check_jsonl_changelog,
    run_cmd,
)


@pytest.fixture
def jsonl_git_repo(tmp_path, monkeypatch):
    """Create a git repo with .rlsbl/changes/ for JSONL changelog testing."""
    repo = tmp_path / "repo"
    repo.mkdir()
    monkeypatch.chdir(repo)

    _run_git(repo, "init", "-q")
    _run_git(repo, "config", "user.email", "test@test.local")
    _run_git(repo, "config", "user.name", "Test")

    # Initial commit
    (repo / "README.md").write_text("# test\n")
    _run_git(repo, "add", "README.md")
    _run_git(repo, "commit", "-q", "-m", "initial")

    # Create a baseline version tag
    _run_git(repo, "tag", "v0.0.0")

    # Set up .rlsbl/changes with empty unreleased.jsonl
    changes = repo / ".rlsbl" / "changes"
    changes.mkdir(parents=True)
    (changes / "unreleased.jsonl").write_text("")

    return repo


class TestRunCmdEntryExists:
    """run_cmd exits 0 when CHANGELOG.md has a matching version heading."""

    def test_exits_zero(self, tmp_project):
        (tmp_project / "package.json").write_text(
            json.dumps({"name": "test-pkg", "version": "1.0.0"})
        )
        (tmp_project / "CHANGELOG.md").write_text("# Changelog\n\n## 1.0.0\n\n- Initial release\n")

        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {})

        assert exc_info.value.code == 0


class TestRunCmdWithoutJsonl:
    """run_cmd warns and exits 0 when JSONL changelog is not set up."""

    def test_warns_no_jsonl(self, tmp_project, capsys):
        (tmp_project / "package.json").write_text(
            json.dumps({"name": "test-pkg", "version": "1.0.0"})
        )
        (tmp_project / "CHANGELOG.md").write_text("# Changelog\n\n## 0.9.0\n\n- Old stuff\n")

        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {})

        assert exc_info.value.code == 0
        captured = capsys.readouterr()
        assert "JSONL changelog not set up" in captured.err

    def test_no_changelog_exits_zero(self, tmp_project, capsys):
        (tmp_project / "package.json").write_text(
            json.dumps({"name": "test-pkg", "version": "1.0.0"})
        )

        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {})

        assert exc_info.value.code == 0


class TestRunCmdNoProjectFiles:
    """run_cmd exits 0 silently when no project files exist."""

    def test_exits_zero(self, tmp_project):
        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {})

        assert exc_info.value.code == 0


class TestAutogeneratedCommitFiltering:
    """Autogenerated commits (with trailer) should be filtered from JSONL coverage checks."""

    def test_autogenerated_commit_skipped(self, jsonl_git_repo):
        """An autogenerated commit passes -- filtered from coverage set."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)
        _run_git(repo, "commit", "--allow-empty", "-m", "auto\n\nAutogenerated: true")
        sha = _git_head(repo)

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None

    def test_multiple_autogenerated_commits_skipped(self, jsonl_git_repo):
        """Multiple autogenerated commits all pass."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)
        _run_git(repo, "commit", "--allow-empty", "-m", "auto1\n\nAutogenerated: true")
        _run_git(repo, "commit", "--allow-empty", "-m", "auto2\n\nAutogenerated: true")
        sha = _git_head(repo)

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None

    def test_non_autogenerated_commit_needs_coverage(self, jsonl_git_repo):
        """A regular commit without the trailer fails with empty JSONL."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: add feature")
        sha = _git_head(repo)

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is not None
        assert "no entries" in error.lower()

    def test_autogenerated_mixed_with_code_commit(self, jsonl_git_repo):
        """Autogenerated commits are filtered; code commits still need coverage."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)

        # Code commit needing coverage
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: add feature")
        code_sha = _git_head(repo)

        # Autogenerated commit (should be filtered out)
        _run_git(repo, "commit", "--allow-empty", "-m", "auto\n\nAutogenerated: true")
        sha = _git_head(repo)

        # Add JSONL entry covering the code commit
        changes_dir = repo / ".rlsbl" / "changes"
        entry = json.dumps({"commits": [code_sha], "user_facing": True,
                            "description": "add feature", "type": "feature"})
        (changes_dir / "unreleased.jsonl").write_text(entry + "\n")

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None

    def test_code_commits_with_jsonl_coverage_pass(self, jsonl_git_repo):
        """Code commits with proper JSONL coverage pass alongside autogenerated commits."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)

        # Regular code commit
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: add feature")
        code_sha = _git_head(repo)

        # Add JSONL entry covering the code commit
        changes_dir = repo / ".rlsbl" / "changes"
        entry = json.dumps({"commits": [code_sha], "user_facing": True,
                            "description": "add feature", "type": "feature"})
        (changes_dir / "unreleased.jsonl").write_text(entry + "\n")
        _run_git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
        _run_git(repo, "commit", "-q", "-m", "changelog entry\n\nAutogenerated: true")

        sha = _git_head(repo)

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None
