"""Tests for monorepo sync command: workflow copying, router generation, cleanup."""

import json
import os
import stat
import subprocess

import pytest

from rlsbl.commands.monorepo import (
    _cmd_init,
    _cmd_add,
    _cmd_sync,
    _generate_router,
    _generate_publish_router,
    _rewrite_trigger,
)
from rlsbl.workspace import load_workspace, WORKSPACE_DIR, WORKSPACE_FILE


CI_WORKFLOW = """\
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo test
"""

PUBLISH_WORKFLOW = """\
name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo publish
"""


def _make_project(base_path, subdir, name=None, ci=True, publish=False):
    """Create a minimal npm project with optional CI and publish workflows."""
    proj_dir = os.path.join(str(base_path), subdir)
    os.makedirs(proj_dir, exist_ok=True)
    pkg_name = name or os.path.basename(subdir)
    with open(os.path.join(proj_dir, "package.json"), "w") as f:
        json.dump({"name": pkg_name, "version": "0.1.0"}, f)

    if ci:
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

    if publish:
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "publish.yml"), "w") as f:
            f.write(PUBLISH_WORKFLOW)

    return subdir


def _init_workspace_with_projects(base_path, project_specs):
    """Initialize workspace and add projects.

    project_specs: list of (subdir, kwargs_dict) tuples.
    Returns list of project names.
    """
    _cmd_init({})
    names = []
    for subdir, kwargs in project_specs:
        _make_project(base_path, subdir, **kwargs)
        name = kwargs.get("name") or os.path.basename(subdir)
        flags = {}
        if "name" in kwargs:
            flags["name"] = kwargs["name"]
        _cmd_add([subdir], flags)
        names.append(name)
    # Commit the setup so safegit/git can work
    subprocess.run(["git", "add", "."], cwd=str(base_path), check=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", "setup workspace"],
        cwd=str(base_path), check=True,
    )
    return names


class TestWorkflowCopy:
    def test_copies_ci_workflow_to_root(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        assert dest.exists()

    def test_trigger_rewrite(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        content = dest.read_text()
        assert "workflow_call" in content
        assert "push:" not in content
        assert "pull_request:" not in content

    def test_header_comment(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        content = dest.read_text()
        assert "# DO NOT EDIT -- generated by rlsbl monorepo sync" in content
        assert "# Source: tooling/.github/workflows/ci.yml" in content

    def test_read_only_permissions(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        mode = stat.S_IMODE(os.stat(str(dest)).st_mode)
        assert mode == 0o444

    def test_warns_missing_workflow(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": False}),
        ])
        # Auto-scaffold creates CI workflows; remove them to test the missing case
        import shutil
        wf_dir = mock_git_repo / "tooling" / ".github" / "workflows"
        if wf_dir.exists():
            shutil.rmtree(str(wf_dir))
        # Also remove the synced copies at root
        root_wf = mock_git_repo / ".github" / "workflows"
        for f in root_wf.glob("tooling-*"):
            f.chmod(0o644)
            f.unlink()
        _cmd_sync({})
        captured = capsys.readouterr()
        assert "Warning" in captured.err
        assert "tooling" in captured.err


class TestRouterGeneration:
    def test_router_generated(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({})
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        assert router.exists()

    def test_router_has_path_filters(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({})
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "tooling: 'tooling/**'" in content
        assert "core: 'core/**'" in content

    def test_router_has_conditional_jobs(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({})
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "needs.detect.outputs.tooling == 'true'" in content
        assert "needs.detect.outputs.core == 'true'" in content
        assert "uses: ./.github/workflows/tooling-ci.yml" in content
        assert "uses: ./.github/workflows/core-ci.yml" in content

    def test_publish_router(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True, "publish": True}),
            ("core", {"ci": True, "publish": True}),
        ])
        _cmd_sync({})
        router = mock_git_repo / ".github" / "workflows" / "publish-router.yml"
        assert router.exists()
        content = router.read_text()
        assert "startsWith(github.event.release.tag_name, 'tooling@v')" in content
        assert "startsWith(github.event.release.tag_name, 'core@v')" in content
        assert "uses: ./.github/workflows/tooling-publish.yml" in content
        assert "uses: ./.github/workflows/core-publish.yml" in content


class TestStaleCleanup:
    def test_removes_stale_workflows(self, mock_git_repo, capsys):
        # Add two projects, sync, then remove one and sync again
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({})
        capsys.readouterr()

        # Verify both exist
        assert (mock_git_repo / ".github" / "workflows" / "tooling-ci.yml").exists()
        assert (mock_git_repo / ".github" / "workflows" / "core-ci.yml").exists()

        # Remove "core" from workspace
        from rlsbl.commands.monorepo import _cmd_remove
        _cmd_remove(["core"], {})
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "remove core"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({})

        # "core-ci.yml" should be removed
        assert not (mock_git_repo / ".github" / "workflows" / "core-ci.yml").exists()
        # "tooling-ci.yml" should still exist
        assert (mock_git_repo / ".github" / "workflows" / "tooling-ci.yml").exists()

        # Deletion should be committed -- working tree must be clean
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=str(mock_git_repo),
            capture_output=True, text=True,
        )
        assert result.stdout.strip() == "", (
            f"Working tree dirty after sync with stale deletion: {result.stdout}"
        )


class TestRewriteTrigger:
    """Unit tests for _rewrite_trigger function."""

    def test_single_line_trigger(self):
        """Single-line 'on: push' is replaced with workflow_call."""
        content = "on: push\n\njobs:\n  test:\n"
        result = _rewrite_trigger(content)
        assert "on:\n  workflow_call:" in result
        assert "on: push" not in result

    def test_single_line_array_trigger(self):
        """Single-line 'on: [push, pull_request]' is replaced with workflow_call."""
        content = "on: [push, pull_request]\n\njobs:\n"
        result = _rewrite_trigger(content)
        assert "on:\n  workflow_call:" in result
        assert "[push, pull_request]" not in result

    def test_no_on_block(self, capsys):
        """Content without 'on:' is returned unchanged with a warning."""
        content = "name: CI\njobs:\n  test:\n"
        result = _rewrite_trigger(content)
        assert result == content
        captured = capsys.readouterr()
        assert "Warning" in captured.err

    def test_multi_line_on_no_jobs(self, capsys):
        """Multi-line on: without jobs: is returned unchanged with a warning."""
        content = "on:\n  push:\n    branches: [main]\n"
        result = _rewrite_trigger(content)
        assert result == content
        captured = capsys.readouterr()
        assert "Warning" in captured.err


class TestAutoCommit:
    def test_sync_commits_changes(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        # Working tree should be clean after sync
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=str(mock_git_repo),
            capture_output=True, text=True,
        )
        assert result.stdout.strip() == ""
