"""Tests for the changelog add/validate/generate subcommands."""

import json
import os
from unittest import mock

import pytest

from conftest import run_git as _run_git, git_head as _git_head, make_commit as _make_commit, make_workspace as _make_workspace
from rlsbl.changelog.files import (
    append_entry,
    get_changes_dir,
    read_unreleased,
)
from rlsbl.changelog.schema import ChangelogEntry
from rlsbl.commands.changelog_cmd import cmd_add, cmd_generate, cmd_validate


@pytest.fixture
def rlsbl_repo(tmp_path, monkeypatch):
    """Create a git repo with .rlsbl/ scaffolding and a baseline version tag."""
    repo = tmp_path / "repo"
    repo.mkdir()
    monkeypatch.chdir(repo)

    _run_git(repo, "init", "-q")
    _run_git(repo, "config", "user.email", "test@test.local")
    _run_git(repo, "config", "user.name", "Test")

    # Initial commit
    (repo / "README.md").write_text("# test\n")
    _run_git(repo, "add", "README.md")
    _run_git(repo, "commit", "-q", "-m", "initial")

    # Create a baseline version tag so <tag>..HEAD works
    _run_git(repo, "tag", "v0.0.0")

    # Set up .rlsbl/changes
    changes = repo / ".rlsbl" / "changes"
    changes.mkdir(parents=True)

    return repo


# ---------------------------------------------------------------------------
# cmd_add tests
# ---------------------------------------------------------------------------


class TestCmdAdd:
    """Tests for cmd_add."""

    def test_valid_entry(self, rlsbl_repo):
        sha = _make_commit(rlsbl_repo)
        flags = {
            "commits": sha[:12],
            "description": "New feature",
            "type": "feature",
            "no-user-facing": False,
        }
        cmd_add(flags)

        entries = read_unreleased(get_changes_dir("."))
        assert len(entries) == 1
        assert entries[0].user_facing is True
        assert entries[0].description == "New feature"
        assert entries[0].type == "feature"
        # Should be resolved to full 40-char hash
        assert len(entries[0].commits[0]) == 40

    def test_non_user_facing(self, rlsbl_repo):
        sha = _make_commit(rlsbl_repo)
        flags = {
            "commits": sha,
            "description": "",
            "type": "",
            "no-user-facing": True,
        }
        cmd_add(flags)

        entries = read_unreleased(get_changes_dir("."))
        assert len(entries) == 1
        assert entries[0].user_facing is False
        assert entries[0].description is None
        assert entries[0].type is None

    def test_invalid_commit_hash(self, rlsbl_repo):
        flags = {
            "commits": "deadbeefdeadbeef",
            "description": "Stuff",
            "type": "fix",
            "no-user-facing": False,
        }
        with pytest.raises(SystemExit) as exc_info:
            cmd_add(flags)
        assert exc_info.value.code == 1

    def test_missing_commits(self, rlsbl_repo):
        flags = {
            "commits": "",
            "description": "Stuff",
            "type": "fix",
            "no-user-facing": False,
        }
        with pytest.raises(SystemExit) as exc_info:
            cmd_add(flags)
        assert exc_info.value.code == 1

    def test_missing_description_for_user_facing(self, rlsbl_repo):
        sha = _make_commit(rlsbl_repo)
        flags = {
            "commits": sha,
            "description": "",
            "type": "fix",
            "no-user-facing": False,
        }
        with pytest.raises(SystemExit) as exc_info:
            cmd_add(flags)
        assert exc_info.value.code == 1

    def test_multiple_commits(self, rlsbl_repo):
        sha1 = _make_commit(rlsbl_repo, "a.txt")
        sha2 = _make_commit(rlsbl_repo, "b.txt")
        flags = {
            "commits": f"{sha1[:8]},{sha2[:8]}",
            "description": "Multi-commit change",
            "type": "feature",
            "no-user-facing": False,
        }
        cmd_add(flags)

        entries = read_unreleased(get_changes_dir("."))
        assert len(entries) == 1
        assert len(entries[0].commits) == 2

    def test_add_auto_commits(self, rlsbl_repo):
        """After adding an entry, commit_files is called with correct args."""
        sha = _make_commit(rlsbl_repo)
        flags = {
            "commits": sha[:12],
            "description": "New feature",
            "type": "feature",
            "no-user-facing": False,
        }
        with mock.patch("rlsbl.commands.changelog_cmd.commit_files") as mock_commit:
            cmd_add(flags)
            mock_commit.assert_called_once()
            call_args = mock_commit.call_args
            assert call_args[0][0] == "changelog: New feature"
            unreleased_path = os.path.join(get_changes_dir("."), "unreleased.jsonl")
            assert call_args[0][1] == [unreleased_path]
            assert call_args[1]["allow_failure"] is True

    def test_add_auto_commit_has_autogenerated_trailer(self, rlsbl_repo):
        """The auto-commit from cmd_add passes autogenerated=True."""
        sha = _make_commit(rlsbl_repo)
        flags = {
            "commits": sha[:12],
            "description": "New feature",
            "type": "feature",
            "no-user-facing": False,
        }
        with mock.patch("rlsbl.commands.changelog_cmd.commit_files") as mock_commit:
            cmd_add(flags)
            mock_commit.assert_called_once()
            assert mock_commit.call_args[1]["autogenerated"] is True

    def test_add_no_commit_flag(self, rlsbl_repo):
        """With --no-commit, commit_files is NOT called."""
        sha = _make_commit(rlsbl_repo)
        flags = {
            "commits": sha[:12],
            "description": "New feature",
            "type": "feature",
            "no-user-facing": False,
            "no-commit": True,
        }
        with mock.patch("rlsbl.commands.changelog_cmd.commit_files") as mock_commit:
            cmd_add(flags)
            mock_commit.assert_not_called()

    def test_add_non_user_facing_commit_message(self, rlsbl_repo):
        """Non-user-facing entries use a generic commit message."""
        sha = _make_commit(rlsbl_repo)
        flags = {
            "commits": sha,
            "description": "",
            "type": "",
            "no-user-facing": True,
        }
        with mock.patch("rlsbl.commands.changelog_cmd.commit_files") as mock_commit:
            cmd_add(flags)
            mock_commit.assert_called_once()
            assert mock_commit.call_args[0][0] == "changelog: non-user-facing entry"


# ---------------------------------------------------------------------------
# cmd_validate tests
# ---------------------------------------------------------------------------


class TestCmdValidate:
    """Tests for cmd_validate."""

    def test_all_pass(self, rlsbl_repo):
        sha = _make_commit(rlsbl_repo)
        changes_dir = get_changes_dir(".")
        append_entry(changes_dir, ChangelogEntry(commits=[sha], user_facing=False))

        # Should exit 0 (no exception)
        cmd_validate({})

    def test_failures(self, rlsbl_repo):
        # Make an unreleased commit with no changelog entry -> coverage fail
        _make_commit(rlsbl_repo)

        with pytest.raises(SystemExit) as exc_info:
            cmd_validate({})
        assert exc_info.value.code == 1

    def test_no_changes_dir(self, tmp_path, monkeypatch):
        """Error when .rlsbl/changes/ does not exist."""
        monkeypatch.chdir(tmp_path)
        with pytest.raises(SystemExit) as exc_info:
            cmd_validate({})
        assert exc_info.value.code == 1

    def test_standalone_no_tag_prefix(self, rlsbl_repo):
        """In standalone mode, validate_unreleased is called without tag_prefix."""
        sha = _make_commit(rlsbl_repo)
        changes_dir = get_changes_dir(".")
        append_entry(changes_dir, ChangelogEntry(commits=[sha], user_facing=False))

        with mock.patch("rlsbl.commands.changelog_cmd.validate_unreleased", wraps=cmd_validate.__module__) as _:
            # Use a more direct approach: mock validate_unreleased and check args
            pass

        with mock.patch("rlsbl.commands.changelog_cmd.validate_unreleased") as mock_validate:
            mock_validate.return_value = {
                "passed": True,
                "checks": {
                    "hashes_resolve": (True, []),
                    "in_range": (True, []),
                    "coverage": (True, []),
                    "no_orphans": (True, []),
                    "schema": (True, []),
                },
            }
            cmd_validate({})
            mock_validate.assert_called_once_with(changes_dir, tag_prefix=None)

    def test_monorepo_passes_tag_prefix(self, tmp_path, monkeypatch):
        """In monorepo context, validate_unreleased receives tag_prefix."""
        monkeypatch.chdir(tmp_path)

        _run_git(tmp_path, "init", "-q")
        _run_git(tmp_path, "config", "user.email", "test@test.local")
        _run_git(tmp_path, "config", "user.name", "Test")

        (tmp_path / "README.md").write_text("# mono\n")
        _run_git(tmp_path, "add", "README.md")
        _run_git(tmp_path, "commit", "-q", "-m", "initial")

        # Create monorepo workspace
        _make_workspace(tmp_path, [{"path": "sub", "name": "mysub"}])

        # Create subproject with changelog dir
        sub_dir = tmp_path / "sub"
        (sub_dir / ".rlsbl" / "changes").mkdir(parents=True)
        (sub_dir / ".rlsbl" / "changes" / "unreleased.jsonl").write_text("")

        _run_git(tmp_path, "add", ".")
        _run_git(tmp_path, "commit", "-q", "-m", "add workspace")
        _run_git(tmp_path, "tag", "mysub@v0.1.0")

        # cd into the subproject
        monkeypatch.chdir(sub_dir)

        sha = _make_commit(tmp_path, "sub/code.py", "subproject change")
        changes_dir = get_changes_dir(".")
        append_entry(changes_dir, ChangelogEntry(commits=[sha], user_facing=False))

        with mock.patch("rlsbl.commands.changelog_cmd.validate_unreleased") as mock_validate:
            mock_validate.return_value = {
                "passed": True,
                "checks": {
                    "hashes_resolve": (True, []),
                    "in_range": (True, []),
                    "coverage": (True, []),
                    "no_orphans": (True, []),
                    "schema": (True, []),
                },
            }
            cmd_validate({})
            mock_validate.assert_called_once_with(changes_dir, tag_prefix="mysub")

    def test_monorepo_unregistered_project_errors(self, tmp_path, monkeypatch):
        """Error when inside a monorepo but not in a registered project."""
        monkeypatch.chdir(tmp_path)

        _run_git(tmp_path, "init", "-q")
        _run_git(tmp_path, "config", "user.email", "test@test.local")
        _run_git(tmp_path, "config", "user.name", "Test")

        (tmp_path / "README.md").write_text("# mono\n")
        _run_git(tmp_path, "add", "README.md")
        _run_git(tmp_path, "commit", "-q", "-m", "initial")

        # Create monorepo workspace with one registered project
        _make_workspace(tmp_path, [{"path": "registered", "name": "myreg"}])
        _run_git(tmp_path, "add", ".")
        _run_git(tmp_path, "commit", "-q", "-m", "add workspace")

        # Create an unregistered dir with .rlsbl/changes so changes_dir_exists passes
        unregistered = tmp_path / "unregistered"
        (unregistered / ".rlsbl" / "changes").mkdir(parents=True)

        monkeypatch.chdir(unregistered)

        with pytest.raises(SystemExit) as exc_info:
            cmd_validate({})
        assert exc_info.value.code == 1


# ---------------------------------------------------------------------------
# cmd_generate tests
# ---------------------------------------------------------------------------


class TestCmdGenerate:
    """Tests for cmd_generate."""

    def test_produces_files(self, rlsbl_repo):
        sha = _make_commit(rlsbl_repo)
        changes_dir = get_changes_dir(".")
        append_entry(
            changes_dir,
            ChangelogEntry(
                commits=[sha],
                user_facing=True,
                description="Added feature X",
                type="feature",
            ),
        )

        cmd_generate({"dry-run": False})

        changelog_path = rlsbl_repo / "CHANGELOG.md"
        assert changelog_path.exists()
        content = changelog_path.read_text()
        assert "Added feature X" in content

    def test_dry_run(self, rlsbl_repo, capsys):
        sha = _make_commit(rlsbl_repo)
        changes_dir = get_changes_dir(".")
        append_entry(
            changes_dir,
            ChangelogEntry(
                commits=[sha],
                user_facing=True,
                description="Feature Y",
                type="feature",
            ),
        )

        cmd_generate({"dry-run": True})

        # Dry-run should NOT write CHANGELOG.md
        changelog_path = rlsbl_repo / "CHANGELOG.md"
        assert not changelog_path.exists()

        # But the preview should be printed
        captured = capsys.readouterr()
        assert "Feature Y" in captured.out
        assert "dry-run" in captured.out

    def test_auto_commits(self, rlsbl_repo):
        """After generating, commit_files is called with changed files."""
        sha = _make_commit(rlsbl_repo)
        changes_dir = get_changes_dir(".")
        append_entry(
            changes_dir,
            ChangelogEntry(
                commits=[sha],
                user_facing=True,
                description="Added feature Z",
                type="feature",
            ),
        )

        with mock.patch("rlsbl.commands.changelog_cmd.commit_files") as mock_commit:
            with mock.patch(
                "rlsbl.commands.changelog_cmd._get_generated_files",
                return_value=["CHANGELOG.md"],
            ):
                cmd_generate({"dry-run": False})
                mock_commit.assert_called_once()
                call_args = mock_commit.call_args
                assert call_args[0][0] == "changelog: regenerate from JSONL"
                assert call_args[0][1] == ["CHANGELOG.md"]
                assert call_args[1]["allow_failure"] is True

    def test_auto_commit_has_autogenerated_trailer(self, rlsbl_repo):
        """The auto-commit from cmd_generate passes autogenerated=True."""
        sha = _make_commit(rlsbl_repo)
        changes_dir = get_changes_dir(".")
        append_entry(
            changes_dir,
            ChangelogEntry(
                commits=[sha],
                user_facing=True,
                description="Added feature Z",
                type="feature",
            ),
        )

        with mock.patch("rlsbl.commands.changelog_cmd.commit_files") as mock_commit:
            with mock.patch(
                "rlsbl.commands.changelog_cmd._get_generated_files",
                return_value=["CHANGELOG.md"],
            ):
                cmd_generate({"dry-run": False})
                mock_commit.assert_called_once()
                assert mock_commit.call_args[1]["autogenerated"] is True

    def test_no_commit_flag(self, rlsbl_repo):
        """With --no-commit, commit_files is NOT called."""
        sha = _make_commit(rlsbl_repo)
        changes_dir = get_changes_dir(".")
        append_entry(
            changes_dir,
            ChangelogEntry(
                commits=[sha],
                user_facing=True,
                description="Added feature W",
                type="feature",
            ),
        )

        with mock.patch("rlsbl.commands.changelog_cmd.commit_files") as mock_commit:
            cmd_generate({"dry-run": False, "no-commit": True})
            mock_commit.assert_not_called()

    def test_dry_run_does_not_commit(self, rlsbl_repo, capsys):
        """Dry-run should NOT trigger auto-commit."""
        sha = _make_commit(rlsbl_repo)
        changes_dir = get_changes_dir(".")
        append_entry(
            changes_dir,
            ChangelogEntry(
                commits=[sha],
                user_facing=True,
                description="Feature Q",
                type="feature",
            ),
        )

        with mock.patch("rlsbl.commands.changelog_cmd.commit_files") as mock_commit:
            cmd_generate({"dry-run": True})
            mock_commit.assert_not_called()

    def test_no_changes_dir(self, tmp_path, monkeypatch):
        """Error when .rlsbl/changes/ does not exist."""
        monkeypatch.chdir(tmp_path)
        with pytest.raises(SystemExit) as exc_info:
            cmd_generate({"dry-run": False})
        assert exc_info.value.code == 1
