"""Implementation of the 'rlsbl commit' command.

Commits files with an Autogenerated trailer, marking them as machine-generated
so the changelog system can exempt them from coverage requirements.
"""

import sys

from ..utils import commit_files


def run_cmd(message, files):
    """Commit files with the Autogenerated: true trailer.

    Returns exit code: 0 on success, 1 on failure.
    """
    success = commit_files(message, list(files))
    if not success:
        sys.exit(1)
