"""Implementation of the 'rlsbl commit' command.

Commits files with an Autogenerated trailer, marking them as machine-generated
so the changelog system can exempt them from coverage requirements.
"""

from ..utils import commit_files


def run_cmd(message, files):
    """Commit files with the Autogenerated: true trailer."""
    commit_files(message, list(files))
