"""Pre-push-check command that verifies CHANGELOG.md contains an entry for the current version before allowing a git push to proceed."""

import fnmatch
import os
import re
import subprocess
import sys

from ..changelog import changes_dir_exists, get_changes_dir, read_unreleased, resolve_hashes
from ..changelog.validate import _is_autogenerated
from ..targets import TARGETS
from ..workspace import find_workspace_root, load_workspace


def _detect_version(dir_path="."):
    """Detect version using registry adapters.

    Returns (version_string, registry_name) or (None, None) if undetectable.
    """
    for name in ("go", "npm", "pypi"):
        reg = TARGETS[name]
        if reg.check_project_exists(dir_path):
            return reg.read_version(dir_path), name
    return None, None


def _check_gitignore_guard(dir_path):
    """Check that rlsbl-managed files are not gitignored.

    Returns an error string listing gitignored paths, or None if all clear.
    """
    paths = [
        os.path.join(dir_path, ".rlsbl", "changes", "unreleased.jsonl"),
        os.path.join(dir_path, ".rlsbl", "changes", ".validated"),
        os.path.join(dir_path, "CHANGELOG.md"),
    ]
    gitignored = []
    for path in paths:
        try:
            result = subprocess.run(
                ["git", "check-ignore", "-q", path],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                gitignored.append(path)
            elif result.returncode == 128:
                # Not in a git repo -- skip gracefully
                return None
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            return None
    if gitignored:
        listed = ", ".join(gitignored)
        return f"rlsbl-managed files are gitignored (must be tracked): {listed}"
    return None



def _get_commit_files(sha):
    """Get the list of files changed by a single commit.

    Returns a list of file paths relative to the repo root, or None on error.
    """
    try:
        result = subprocess.run(
            ["git", "diff-tree", "--no-commit-id", "--name-only", "-r", sha],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode != 0:
            return None
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return None

    return [line.strip() for line in result.stdout.strip().splitlines() if line.strip()]


def _filter_commits_for_project(commits, project):
    """Filter commits to only those that touch files belonging to a project.

    Takes a set of commit SHAs and a project dict. For each commit, gets its
    changed files and checks whether any file matches the project (by path
    prefix or watch globs).

    Returns the subset of commits where at least one file belongs to the project.
    """
    filtered = set()
    for sha in commits:
        files = _get_commit_files(sha)
        if files is None:
            # Cannot determine files -- include the commit to be safe
            filtered.add(sha)
            continue
        for filepath in files:
            if _file_matches_project(filepath, project):
                filtered.add(sha)
                break
    return filtered


def _check_jsonl_changelog(dir_path, refs, pushed_commits=None):
    """Check JSONL changelog coverage for commits being pushed.

    Verifies that every commit in the push range exists in at least one
    unreleased.jsonl entry's commits list.

    When pushed_commits is provided, uses that set directly instead of
    calling _get_pushed_commits(refs). This allows callers (e.g. monorepo
    check) to pass a pre-filtered set of commits.

    Returns None on success, or an error message string on failure.
    """
    changes_dir = get_changes_dir(dir_path)
    entries = read_unreleased(changes_dir)

    # Get pushed commits from the refs, or use the provided set
    if pushed_commits is None:
        pushed_commits = _get_pushed_commits(refs)
    if pushed_commits is None:
        return None  # Could not determine pushed commits -- skip

    # Filter out autogenerated commits (release infrastructure) --
    # these don't need JSONL coverage.
    commits_needing_coverage = {sha for sha in pushed_commits if not _is_autogenerated(sha)}
    if not commits_needing_coverage:
        return None

    if not entries:
        return "unreleased.jsonl has no entries"

    # Collect all hashes from entries and resolve them
    all_hashes = []
    for entry in entries:
        all_hashes.extend(entry.commits)
    resolved = resolve_hashes(all_hashes)
    covered_shas = {full for full in resolved.values() if full is not None}

    missing = []
    for sha in commits_needing_coverage:
        if sha not in covered_shas:
            missing.append(sha[:12])

    if missing:
        return f"JSONL changelog missing coverage for {len(missing)} commit(s): {', '.join(missing[:5])}"

    return None


def _get_pushed_commits(refs):
    """Get the set of commit SHAs being pushed.

    Returns a set of full 40-char SHAs, or None on error.
    """
    zero_sha = "0" * 40
    commits = set()

    for local_sha, remote_sha in refs:
        if local_sha == zero_sha:
            continue  # Branch deletion

        try:
            if remote_sha == zero_sha:
                # New branch: commits not on any remote
                result = subprocess.run(
                    ["git", "log", "--format=%H", local_sha, "--not", "--remotes"],
                    capture_output=True, text=True, timeout=30,
                )
            else:
                result = subprocess.run(
                    ["git", "log", "--format=%H", f"{remote_sha}..{local_sha}"],
                    capture_output=True, text=True, timeout=30,
                )
            if result.returncode == 0:
                for line in result.stdout.strip().splitlines():
                    line = line.strip()
                    if line:
                        commits.add(line)
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return None

    return commits


def _read_stdin_lines():
    """Read raw pre-push hook stdin lines.

    Returns a list of non-empty lines, or None if stdin is not readable
    or empty.
    """
    try:
        if sys.stdin.isatty():
            return None
        raw = sys.stdin.read().strip()
    except (AttributeError, OSError):
        return None

    if not raw:
        return None

    lines = [line for line in raw.splitlines() if line.strip()]
    return lines if lines else None


def _has_version_tag_push(stdin_lines):
    """Check whether any stdin line is pushing a version tag.

    Version tags match ``refs/tags/v*`` (single-project) or
    ``refs/tags/*@v*`` (monorepo scoped tags like ``mylib@v1.2.3``).

    Returns True if at least one line pushes a version tag.
    """
    pattern = re.compile(r"^refs/tags/(v\d|[^/]+@v\d)")
    for line in stdin_lines:
        parts = line.split()
        if len(parts) >= 4:
            local_ref = parts[0]
            if pattern.match(local_ref):
                return True
    return False


def _parse_stdin_refs(stdin_lines=None):
    """Parse pre-push hook stdin to extract (local_sha, remote_sha) pairs.

    Each line is: <local ref> <local sha> <remote ref> <remote sha>

    When *stdin_lines* is provided (a list of raw lines), parses those
    directly instead of reading stdin.  When omitted, reads stdin via
    ``_read_stdin_lines()``.

    Returns a list of (local_sha, remote_sha) tuples, or None if the
    input is empty or unreadable.
    """
    if stdin_lines is None:
        stdin_lines = _read_stdin_lines()
    if stdin_lines is None:
        return None

    refs = []
    for line in stdin_lines:
        parts = line.split()
        if len(parts) >= 4:
            local_sha = parts[1]
            remote_sha = parts[3]
            refs.append((local_sha, remote_sha))
    return refs if refs else None


def _get_changed_files(refs):
    """Get the list of files changed across all pushed refs.

    Returns a set of file paths relative to the repo root.
    """
    zero_sha = "0" * 40
    changed = set()

    for local_sha, remote_sha in refs:
        if local_sha == zero_sha:
            # Branch being deleted -- nothing to check
            continue

        try:
            if remote_sha == zero_sha:
                # New branch: get files in commits not yet on any remote
                result = subprocess.run(
                    ["git", "log", "--name-only", "--pretty=format:", local_sha,
                     "--not", "--remotes"],
                    capture_output=True, text=True, timeout=30,
                )
            else:
                result = subprocess.run(
                    ["git", "diff", "--name-only", f"{remote_sha}..{local_sha}"],
                    capture_output=True, text=True, timeout=30,
                )
            if result.returncode == 0:
                for f in result.stdout.strip().splitlines():
                    f = f.strip()
                    if f:
                        changed.add(f)
        except (subprocess.TimeoutExpired, FileNotFoundError):
            # If git fails, fall back to single-project behavior
            return None

    return changed


def _file_matches_project(filepath, project):
    """Check whether a file path belongs to a project.

    A file belongs to a project if:
    - It starts with the project's path prefix, OR
    - It matches any of the project's watch globs
    """
    proj_path = project["path"]
    # Normalize: ensure prefix ends with /
    prefix = proj_path.rstrip("/") + "/"
    if filepath == proj_path or filepath.startswith(prefix):
        return True

    for glob_pattern in project.get("watch", []):
        if fnmatch.fnmatch(filepath, glob_pattern):
            return True

    return False


def _affected_projects(changed_files, projects):
    """Determine which projects are affected by the changed files.

    Returns a list of project dicts that have at least one changed file.
    """
    affected = []
    for proj in projects:
        for f in changed_files:
            if _file_matches_project(f, proj):
                affected.append(proj)
                break
    return affected


def _run_monorepo_check(workspace_root, projects, changed_files, refs=None):
    """Check changelogs for all affected monorepo projects.

    Filters pushed commits per project so that a commit touching only one
    project does not require changelog coverage in other projects.

    Returns exit code 0 on success, 1 if any project fails.
    """
    affected = _affected_projects(changed_files, projects)
    if not affected:
        sys.exit(0)

    if refs is None:
        sys.exit(0)

    # Get all pushed commits once, then filter per project
    all_pushed = _get_pushed_commits(refs)
    if all_pushed is None:
        sys.exit(0)

    failures = []
    for proj in affected:
        proj_dir = os.path.join(workspace_root, proj["path"])

        # Gitignore guard: block if rlsbl-managed files are gitignored
        gitignore_error = _check_gitignore_guard(proj_dir)
        if gitignore_error:
            failures.append((proj["name"], "?", gitignore_error))
            continue

        if not changes_dir_exists(proj_dir):
            continue  # JSONL not set up for this project -- skip

        # Filter to only commits that touch this project's files
        proj_commits = _filter_commits_for_project(all_pushed, proj)
        if not proj_commits:
            continue  # No commits relevant to this project

        error = _check_jsonl_changelog(proj_dir, refs, pushed_commits=proj_commits)

        if error:
            version, _ = _detect_version(proj_dir)
            failures.append((proj["name"], version or "?", error))

    if not failures:
        sys.exit(0)

    for name, version, error in failures:
        print(f"Error: {name}: {error}.", file=sys.stderr)
        print(f"Add JSONL changelog entries covering all pushed commits for {name}.",
              file=sys.stderr)
    sys.exit(1)


def run_cmd(registry, args, flags):
    """Check that CHANGELOG.md has an entry for the current project version.

    In monorepo mode (when a workspace root is detected), parses the pushed
    ref range from stdin to determine which projects are affected, then checks
    each affected project's changelog independently.

    In single-project mode, checks the current directory's changelog.

    Exits 1 if any changelog entry is missing; exits 0 silently on success.
    """
    # Read stdin once -- used for tag detection and ref parsing
    stdin_lines = _read_stdin_lines()

    # Optimisation: if the push includes a version tag, skip JSONL checks
    # entirely.  The release flow (rlsbl release) already validates
    # changelog coverage before pushing, so re-checking is redundant.
    if stdin_lines is not None and _has_version_tag_push(stdin_lines):
        sys.exit(0)

    # Detect monorepo context
    workspace_root = find_workspace_root(".")
    if workspace_root:
        refs = _parse_stdin_refs(stdin_lines)
        if refs is not None:
            changed_files = _get_changed_files(refs)
            if changed_files is not None:
                projects = load_workspace(workspace_root)
                _run_monorepo_check(workspace_root, projects, changed_files, refs=refs)
                # _run_monorepo_check always calls sys.exit, so this is unreachable

    # Single-project fallback

    # Gitignore guard: block push if rlsbl-managed files are gitignored
    gitignore_error = _check_gitignore_guard(".")
    if gitignore_error:
        print(f"Error: {gitignore_error}", file=sys.stderr)
        sys.exit(1)

    if not changes_dir_exists("."):
        # JSONL changelog not set up -- warn but don't block
        print("Warning: JSONL changelog not set up. Run 'rlsbl scaffold --update' to create .rlsbl/changes/", file=sys.stderr)
        sys.exit(0)

    # JSONL mode: check commit coverage
    refs = _parse_stdin_refs(stdin_lines)
    if refs is not None:
        error = _check_jsonl_changelog(".", refs)
        if error is None:
            sys.exit(0)
        print(f"Error: {error}.", file=sys.stderr)
        print("Add JSONL changelog entries covering all pushed commits.", file=sys.stderr)
        sys.exit(1)
    # No refs available (not called from pre-push hook) -- skip
    sys.exit(0)
